### ISSUE TITLE
Úkoly z páté lekce

### ISSUE THREAD

**Issue by MartinaHytychova** [MartinaHytychova/python-012021.#6]

**Comment by pesikj** [comment]
Ahoj Martino,

### Příklad 21

Na řádku 18 ti v řetězci chybí složené závorky plus je to akcie z americké burzy, takže cena je v dolarech :-) Jinak super včetně doplňku :-)

### Příklad 22

Řádek 11 můžeš jednodušeji zapsat takto:

```python

death_char = data.set_index('Name')

```

Jinak super :-)

### Příklad 23

U výběru extrémních hodnot je jedna zrada. Píšeš všechny podmínky najednou a obecně platí, že logické násobení `&` má přednost před logickým sčítáním `|`, což je ale opak toho, co chceme. Do tvého výstupu se tedy vetřou hodnoty, které tam nechceme. Lze to vyřešit stejně jako u klasického problému násobení vs. sčítání - přidáním závorek. Ale to jsme spolu neprobírali a neberu to jako chybu.

Druhá možnost je pracovat s tabulkou získanou v kroku jedna, kde je vybrán konkrétní den a dál by stačilo přidat podmínku na hodnoty. :-)

```python

in_range = (data['date'] == '2021-03-10') & ((data['total_vaccinations'] > 100000) | (data['total_vaccinations'] < 100))
print(data[in_range][col])

```

Plus u posledního řádku chybí jeden pár závorek :-)

```python

print(data[japan_dates][['date', 'total_vaccinations']])

```

### Příklad 24

Super :-)

### Příklad 25

Super, máš moc hezky zpracované výpisy. :-)

### Shrnutí

Příklady máš super zpracované včetně rozšíření, připisuji 5 bodů :-)

**Comment by MartinaHytychova** [comment]
@pesikj  děkuji, upravila jsem si :)
