### ISSUE TITLE
Úkoly 8. lekce projekt

### ISSUE THREAD

**Issue by MartinaHytychova** [MartinaHytychova/python-012021.#9]

**Comment by pesikj** [comment]
Ahoj Martino,

naprogramováno je vše ok, ale projekt neměl správnou strukturu, asi kvůli chybě při vytváření, kterou jsme řešili na konzultaci. Nahrál jsem tedy do adresáře `project_jirka` projekt vytvořený Django nástroji a pak jsem tam překopíroval tvůj kód ze souborů `views.py`, `urls.py` (2x). Jinak by s tím v budoucnu byly problémy. Udělej si prosím operace fetch a pull (v PyCharmu v menu git - nejprve Fetch a poté Pull). Můžeš si pak projekt zkopírovat do svého adresáře a přidat modely.

Doufám, že nevadí, že jsem se ti tam takhle vetřel, ale myslím, že bys dříve nebo později narazila na problém s migracemi. :-)

**Comment by pesikj** [comment]
Jinak jsem prošel tvůj kód a vše je ok, takže připisuji 5 bodů.

**Comment by MartinaHytychova** [comment]
Ahoj, já jsem si tvého komentáře všimla až teď a už jsem to nestihla pullnout s tvými změnami. Moje verze mi fungovala, ale při pushnutí mi to nabízelo zmergovat změny, takže jsem to zmergovala, ale asi špatně, protože teď mi to nefunguje.

**Comment by MartinaHytychova** [comment]
opraveno

**Comment by pesikj** [comment]
Super, promiň, že jsem nahrál i změny k tobě, chtěl jsem to nahrát jen do své složky. Už mi to funguje a ta struktura teď vypadá dobře, takže už bys problémy mít neměla :-)
